# Housing Rental Analysis for San Francisco

In this challenge, your job is to use your data visualisation skills, including aggregation, interactive visualisations, and geospatial analysis, to find properties in the San Francisco market that are viable investment opportunities.

## Background

**Proptech**, the application of technology to real-estate markets, is an innovative domain in the fintech industry. Assume that you’re an analyst at a proptech company that wants to offer an instant, one-click service for people to buy properties and then rent them. The company wants to have a trial of this offering in the San Francisco real estate market. If the service proves popular, they can then expand to other markets.

Your job is to use your data visualisation skills, including aggregation, interactive visualisations, and geospatial analysis, to find properties in the San Francisco market that are viable investment opportunities.

In [93]:
# Import the required libraries and dependencies
import pandas as pd
import hvplot.pandas
from pathlib import Path

## Import the data 

In [94]:
# Using the read_csv function and Path module, create a DataFrame 
# by importing the sfo_neighborhoods_census_data.csv file from the Resources folder
sfo_data_df = pd.read_csv(
    Path('../Resources/sfo_neighborhoods_census_data.csv') # Read in the input file
)

# Review the first and last five rows of the DataFrame
display( "***Head***", sfo_data_df.head() )
display( "***Tail***", sfo_data_df.tail() )

'***Head***'

year      neighborhood  sale_price_sqr_foot  housing_units  gross_rent
0  2010      Alamo Square           291.182945         372560        1239
1  2010        Anza Vista           267.932583         372560        1239
2  2010           Bayview           170.098665         372560        1239
3  2010  Buena Vista Park           347.394919         372560        1239
4  2010  Central Richmond           319.027623         372560        1239

'***Tail***'

year            neighborhood  sale_price_sqr_foot  housing_units  \
392  2016          Telegraph Hill           903.049771         384242   
393  2016              Twin Peaks           970.085470         384242   
394  2016  Van Ness/ Civic Center           552.602567         384242   
395  2016       Visitacion Valley           328.319007         384242   
396  2016           Westwood Park           631.195426         384242   

     gross_rent  
392        4390  
393        4390  
394        4390  
395        4390  
396        4390

In [95]:
sfo_data_df.info

<bound method DataFrame.info of      year            neighborhood  sale_price_sqr_foot  housing_units  \
0    2010            Alamo Square           291.182945         372560   
1    2010              Anza Vista           267.932583         372560   
2    2010                 Bayview           170.098665         372560   
3    2010        Buena Vista Park           347.394919         372560   
4    2010        Central Richmond           319.027623         372560   
..    ...                     ...                  ...            ...   
392  2016          Telegraph Hill           903.049771         384242   
393  2016              Twin Peaks           970.085470         384242   
394  2016  Van Ness/ Civic Center           552.602567         384242   
395  2016       Visitacion Valley           328.319007         384242   
396  2016           Westwood Park           631.195426         384242   

     gross_rent  
0          1239  
1          1239  
2          1239  
3          1239  
4

---

## Calculate and Plot the Housing Units per Year

For this part of the assignment, use numerical and visual aggregation to calculate the number of housing units per year, and then visualise the results as a bar chart. To do so, complete the following steps:

1. Use the `groupby` function to group the data by year. Aggregate the results by the `mean` of the groups.

2. Use the `hvplot` function to plot the `housing_units_by_year` DataFrame as a bar chart. Make the x-axis represent the `year` and the y-axis represent the `housing_units`.

3. Style and format the line plot to ensure a professionally styled visualisation.

4. Note that your resulting plot should appear similar to the following image:

![A screenshot depicts an example of the resulting bar chart.](./Images/zoomed-housing-units-by-year.png)

5. Answer the following question:

    * What’s the overall trend in housing units over the period that you’re analysing?



### Step 1: Use the `groupby` function to group the data by year. Aggregate the results by the `mean` of the groups.

In [96]:
# Create a numerical aggregation that groups the data by the year and then averages the results.
housing_units_by_year = sfo_data_df[["year","housing_units"]].groupby("year").mean()

# Review the DataFrame
housing_units_by_year

housing_units
year               
2010       372560.0
2011       374507.0
2012       376454.0
2013       378401.0
2014       380348.0
2015       382295.0
2016       384242.0

### Step 2: Use the `hvplot` function to plot the `housing_units_by_year` DataFrame as a bar chart. Make the x-axis represent the `year` and the y-axis represent the `housing_units`.

### Step 3: Style and format the line plot to ensure a professionally styled visualisation.

In [110]:
# Create a visual aggregation to explore the housing units by year
min_year = sfo_data_df["year"].min()   # Get the earliest year in the data to use in the title as "from" year
max_year = sfo_data_df["year"].max()   # Get the latest year in the data to use in the title as "to" year

# Adjust the plot's minimum y-axis to better show the scale of comparative change from one year to the next
min_y_axis = sfo_data_df["housing_units"].min()  # Get the lowest value in our Y axis range
min_y_axis -= (min_y_axis*0.025)                 # Set the plot's min_y_axis value to 2.5% below that value

fig1_title = f"Figure 1 - Housing Units in San Francisco from {min_year} to {max_year}" # Construct the title using the variable years 
fig1 = housing_units_by_year.groupby("year").mean().hvplot.bar(                         # Group the data by year and get the average then create the plot
    xlabel="Year",                # Set the x axis label
    ylabel="Housing Units",       # Set the y axis label
    ylim=(min_y_axis,None),       # Set the y axis minimum limit but leave the maximum to automatic
    color="blue",                 # Set the bar to blue
    rot=0,                        # Set the rotation
    height=500,                   # Set the chart height
    width=1000                    # Set the chart width
).opts( yformatter='%.0f',        # Format the numbers in standard notation rather than scientific notation which is the default
        title=fig1_title )        # Set the chart's title

fig1 # Display the plot

:Bars   [year]   (housing_units)

In [104]:
# Determine the year-on-year percentage change
housing_units_by_year.groupby("year")["housing_units"].mean().pct_change().dropna()

year
2011    0.005226
2012    0.005199
2013    0.005172
2014    0.005145
2015    0.005119
2016    0.005093
Name: housing_units, dtype: float64

### Step 5: Answer the following question:

**Question:** What is the overall trend in housing_units over the period being analysed?

**Answer:** From 2010 to 2016 there has been a year-on-year increase of about 0.5% per year.

---

## Calculate and Plot the Average Sale Prices per Square Foot

For this part of the assignment, use numerical and visual aggregation to calculate the average prices per square foot, and then visualise the results as a bar chart. To do so, complete the following steps:

1. Group the data by year, and then average the results. What’s the lowest gross rent that’s reported for the years that the DataFrame includes?

2. Create a new DataFrame named `prices_square_foot_by_year` by filtering out the “housing_units” column. The new DataFrame should include the averages per year for only the sale price per square foot and the gross rent.

3. Use hvPlot to plot the `prices_square_foot_by_year` DataFrame as a line plot.

    > **Hint** This single plot will include lines for both `sale_price_sqr_foot` and `gross_rent`.

4. Style and format the line plot to ensure a professionally styled visualisation.

5. Note that your resulting plot should appear similar to the following image:

![A screenshot depicts an example of the resulting plot.](./Images/avg-sale-px-sq-foot-gross-rent.png)

6. Use both the `prices_square_foot_by_year` DataFrame and interactive plots to answer the following questions:

    * Did any year experience a drop in the average sale price per square foot compared to the previous year?

    * If so, did the gross rent increase or decrease during that year?



### Step 1: Group the data by year, and then average the results.

In [105]:
# Create a numerical aggregation by grouping the data by year and averaging the results
prices_square_foot_by_year = sfo_data_df[["year","sale_price_sqr_foot"]].groupby("year").mean()

# Review the resulting DataFrame
prices_square_foot_by_year

sale_price_sqr_foot
year                     
2010           369.344353
2011           341.903429
2012           399.389968
2013           483.600304
2014           556.277273
2015           632.540352
2016           697.643709

**Question:** What is the lowest gross rent reported for the years included in the DataFrame?

**Answer:** $341.90  _(See below for calculations)_

In [106]:
lowest_rent =  prices_square_foot_by_year["sale_price_sqr_foot"].min()

print(f"The lowest gross rent reported for the years included in the DataFrame is ${lowest_rent:0,.2f} per sqr foot" )

The lowest gross rent reported for the years included in the DataFrame is $341.90 per sqr foot


### Step 2: Create a new DataFrame named `prices_square_foot_by_year` by filtering out the “housing_units” column. The new DataFrame should include the averages per year for only the sale price per square foot and the gross rent.

In [107]:
# Filter out the housing_units column, creating a new DataFrame 
# Keep only sale_price_sqr_foot and gross_rent averages per year
prices_square_foot_by_year =  sfo_data_df[["year","sale_price_sqr_foot","gross_rent"]].groupby("year").mean()

# Review the DataFrame
prices_square_foot_by_year

sale_price_sqr_foot  gross_rent
year                                 
2010           369.344353      1239.0
2011           341.903429      1530.0
2012           399.389968      2324.0
2013           483.600304      2971.0
2014           556.277273      3528.0
2015           632.540352      3739.0
2016           697.643709      4390.0

### Step 3: Use hvPlot to plot the `prices_square_foot_by_year` DataFrame as a line plot.

> **Hint** This single plot will include lines for both `sale_price_sqr_foot` and `gross_rent`

### Step 4: Style and format the line plot to ensure a professionally styled visualisation.


In [112]:
# Plot prices_square_foot_by_year. 
fig2_title = f"Figure 2 - Sale Price Per Square Foot and Average Gross Rent - {min_year}-{max_year} - San Francisco"
fig2 = prices_square_foot_by_year.hvplot.line(
    xlabel="Year",                                        # Set the x axis label
    group_label="Legend",                                 # Change the legend's title from the default which is "Variable" to "Legend"    
    ylabel="Gross Rent / Sale Price Per Square Foot",     # Set the y axis label
    height=500,                                           # Set the chart height
    width=1000                                            # Set the chart width
).opts( yformatter='%.0f',                                # Format the numbers in standard notation rather than scientific notation which is the default
        title=fig2_title )                                # Set the chart's title

# Inclued labels for the x- and y-axes, and a title.
fig2

:NdOverlay   [Legend]
   :Curve   [year]   (value)

### Step 6: Use both the `prices_square_foot_by_year` DataFrame and interactive plots to answer the following questions:

**Question:** Did any year experience a drop in the average sale price per square foot compared to the previous year?

**Answer:** In 2011, there was a 7.4% drop in the average sale price per square foot in San Francisco . _(See below for calculations)_

In [115]:
housing_pct_change = prices_square_foot_by_year.groupby("year").mean().pct_change().dropna()
housing_pct_change

sale_price_sqr_foot  gross_rent
year                                 
2011            -0.074296    0.234867
2012             0.168137    0.518954
2013             0.210847    0.278399
2014             0.150283    0.187479
2015             0.137095    0.059807
2016             0.102924    0.174111

In [116]:
print("Years that experienced a drop in the average sale price per square foot compared to the previous year:")
housing_pct_change[housing_pct_change["sale_price_sqr_foot"]<0].dropna()

Years that experienced a drop in the average sale price per square foot compared to the previous year:


sale_price_sqr_foot  gross_rent
year                                 
2011            -0.074296    0.234867

**Question:** If so, did the gross rent increase or decrease during that year?

**Answer:** The gross rent increased by 23.5% the same year.

---

## Compare the Average Sale Prices by Neighborhood

For this part of the assignment, use interactive visualisations and widgets to explore the average sale price per square foot by neighborhood. To do so, complete the following steps:

1. Create a new DataFrame that groups the original DataFrame by year and neighborhood. Aggregate the results by the `mean` of the groups.

2. Filter out the “housing_units” column to create a DataFrame that includes only the `sale_price_sqr_foot` and `gross_rent` averages per year.

3. Create an interactive line plot with hvPlot that visualises both `sale_price_sqr_foot` and `gross_rent`. Set the x-axis parameter to the year (`x="year"`). Use the `groupby` parameter to create an interactive widget for `neighborhood`.

4. Style and format the line plot to ensure a professionally styled visualisation.

5. Note that your resulting plot should appear similar to the following image:

![A screenshot depicts an example of the resulting plot.](./Images/pricing-info-by-neighborhood.png)

6. Use the interactive visualisation to answer the following question:

    * For the Anza Vista neighborhood, is the average sale price per square foot for 2016 more or less than the price that’s listed for 2012? 


### Step 1: Create a new DataFrame that groups the original DataFrame by year and neighborhood. Aggregate the results by the `mean` of the groups.

In [120]:
# Group by year and neighborhood and then create a new dataframe of the mean values
prices_by_year_by_neighborhood = sfo_data_df.groupby(["year", "neighborhood"]).mean()

# Review the DataFrame
prices_by_year_by_neighborhood

sale_price_sqr_foot  housing_units  gross_rent
year neighborhood                                                          
2010 Alamo Square                     291.182945       372560.0      1239.0
     Anza Vista                       267.932583       372560.0      1239.0
     Bayview                          170.098665       372560.0      1239.0
     Buena Vista Park                 347.394919       372560.0      1239.0
     Central Richmond                 319.027623       372560.0      1239.0
...                                          ...            ...         ...
2016 Telegraph Hill                   903.049771       384242.0      4390.0
     Twin Peaks                       970.085470       384242.0      4390.0
     Van Ness/ Civic Center           552.602567       384242.0      4390.0
     Visitacion Valley                328.319007       384242.0      4390.0
     Westwood Park                    631.195426       384242.0      4390.0

[397 rows x 3 columns]

### Step 2: Filter out the “housing_units” column to create a DataFrame that includes only the `sale_price_sqr_foot` and `gross_rent` averages per year.

In [121]:
# Filter out the housing_units
prices_by_year_by_neighborhood = prices_by_year_by_neighborhood.drop(columns=["housing_units"])
# Review the first and last five rows of the DataFrame
display( prices_by_year_by_neighborhood.head() )
display( prices_by_year_by_neighborhood.tail() )

sale_price_sqr_foot  gross_rent
year neighborhood                                     
2010 Alamo Square               291.182945      1239.0
     Anza Vista                 267.932583      1239.0
     Bayview                    170.098665      1239.0
     Buena Vista Park           347.394919      1239.0
     Central Richmond           319.027623      1239.0

sale_price_sqr_foot  gross_rent
year neighborhood                                           
2016 Telegraph Hill                   903.049771      4390.0
     Twin Peaks                       970.085470      4390.0
     Van Ness/ Civic Center           552.602567      4390.0
     Visitacion Valley                328.319007      4390.0
     Westwood Park                    631.195426      4390.0

### Step 3: Create an interactive line plot with hvPlot that visualises both `sale_price_sqr_foot` and `gross_rent`. Set the x-axis parameter to the year (`x="year"`). Use the `groupby` parameter to create an interactive widget for `neighborhood`.

### Step 4: Style and format the line plot to ensure a professionally styled visualisation.

In [317]:
# Using hvplot to create an interactive line plot of the average price per square foot
# The plot will have a dropdown selector for the neighborhood

fig3_title = f"Figure 3 - Sale Price Per Square Foot and Average Gross Rent - {min_year}-{max_year} - By Neighborhood" # Construct the title based on fixed and variable data
fig3 = prices_by_year_by_neighborhood.hvplot.line(
    x="year",                                           # Force the x axis to the Year
    y=["sale_price_sqr_foot", "gross_rent"],            # Plot both the sales price and rent on the Y axis
    group_label="Legend",                               # Change the legend's title from the default which is "Variable" to "Legend"
    groupby="neighborhood",                             # Set the dropdown selector to allow selection of Neighborhood
    xlabel="Year",                                      # Label the x axis
    ylabel="Gross Rent / Sale Price Per Square Foot",   # Label the y axis
    height=500,
    width=800
).opts( yformatter='%.0f',                              # Set numbers to standard notation
        title=fig3_title)                               # Set the Title based

fig3 # Display the plot

:DynamicMap   [neighborhood]
   :NdOverlay   [Legend]
      :Curve   [year]   (value)

### Step 6: Use the interactive visualisation to answer the following question:

**Question:** For the Anza Vista neighborhood, is the average sale price per square foot for 2016 more or less than the price that’s listed for 2012? 

**Answer:** The average sale price per square foot for the Anza Vista neighborhood was `$344.491` in 2012 versus `$88.402` in 2016, therefore the price was less in 2016 compared to 2012.

---

## Build an Interactive Neighborhood Map

For this part of the assignment, explore the geospatial relationships in the data by using interactive visualisations with hvPlot and GeoViews. To build your map, use the `sfo_data_df` DataFrame (created during the initial import), which includes the neighborhood location data with the average prices. To do all this, complete the following steps:

1. Read the `neighborhood_coordinates.csv` file from the `Resources` folder into the notebook, and create a DataFrame named `neighborhood_locations_df`. Be sure to set the `index_col` of the DataFrame as “Neighborhood”.

2. Using the original `sfo_data_df` Dataframe, create a DataFrame named `all_neighborhood_info_df` that groups the data by neighborhood. Aggregate the results by the `mean` of the group.

3. Review the two code cells that concatenate the `neighborhood_locations_df` DataFrame with the `all_neighborhood_info_df` DataFrame. Note that the first cell uses the [Pandas concat function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html) to create a DataFrame named `all_neighborhoods_df`. The second cell cleans the data and sets the “Neighborhood” column. Be sure to run these cells to create the `all_neighborhoods_df` DataFrame, which you’ll need to create the geospatial visualisation.

4. Using hvPlot with GeoViews enabled, create a `points` plot for the `all_neighborhoods_df` DataFrame. Be sure to do the following:

    * Set the `size` parameter to “sale_price_sqr_foot”.

    * Set the `color` parameter to “gross_rent”.

    * Set the `size_max` parameter to “25”.

    * Set the `zoom` parameter to “11”.

Note that your resulting plot should appear similar to the following image:

![A screenshot depicts an example of a scatter plot created with hvPlot and GeoViews.](./Images/6-4-geoviews-plot.png)

5. Use the interactive map to answer the following question:

    * Which neighborhood has the highest gross rent, and which has the highest sale price per square foot?


### Step 1: Read the `neighborhood_coordinates.csv` file from the `Resources` folder into the notebook, and create a DataFrame named `neighborhood_locations_df`. Be sure to set the `index_col` of the DataFrame as “Neighborhood”.

In [131]:
# Load neighborhoods coordinates data
neighborhood_locations_df = pd.read_csv( Path('../Resources/neighborhoods_coordinates.csv'), index_col="Neighborhood" )

# Review the DataFrame
display( neighborhood_locations_df.info() )
display( neighborhood_locations_df.head() )

<class 'pandas.core.frame.DataFrame'>
Index: 73 entries, Alamo Square to Yerba Buena
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Lat     73 non-null     float64
 1   Lon     73 non-null     float64
dtypes: float64(2)
memory usage: 1.7+ KB


None

Lat         Lon
Neighborhood                          
Alamo Square     37.791012 -122.402100
Anza Vista       37.779598 -122.443451
Bayview          37.734670 -122.401060
Bayview Heights  37.728740 -122.410980
Bernal Heights   37.728630 -122.443050

### Step 2: Using the original `sfo_data_df` Dataframe, create a DataFrame named `all_neighborhood_info_df` that groups the data by neighborhood. Aggregate the results by the `mean` of the group.

In [511]:
# Calculate the mean values for each neighborhood
all_neighborhood_info_df = sfo_data_df[["neighborhood", "sale_price_sqr_foot", "gross_rent"]].groupby("neighborhood").mean()


# Review the resulting DataFrame
display( all_neighborhood_info_df )

sale_price_sqr_foot   gross_rent
neighborhood                                        
Alamo Square                 366.020712  2817.285714
Anza Vista                   373.382198  3031.833333
Bayview                      204.588623  2318.400000
Bayview Heights              590.792839  3739.000000
Bernal Heights               576.746488  3080.333333
...                                 ...          ...
West Portal                  498.488485  2515.500000
Western Addition             307.562201  2555.166667
Westwood Highlands           533.703935  2250.500000
Westwood Park                687.087575  3959.000000
Yerba Buena                  576.709848  2555.166667

[73 rows x 2 columns]

### Step 3: Review the two code cells that concatenate the `neighborhood_locations_df` DataFrame with the `all_neighborhood_info_df` DataFrame. 

Note that the first cell uses the [Pandas concat function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html) to create a DataFrame named `all_neighborhoods_df`. 

The second cell cleans the data and sets the “Neighborhood” column. 

Be sure to run these cells to create the `all_neighborhoods_df` DataFrame, which you’ll need to create the geospatial visualisation.

In [512]:
# Using the Pandas `concat` function, join the 
# neighborhood_locations_df and the all_neighborhood_info_df DataFrame
# The axis of the concatenation is "columns".
# The concat function will automatially combine columns with
# identical information, while keeping the additional columns.
all_neighborhoods_df = pd.concat(
    [neighborhood_locations_df, all_neighborhood_info_df], 
    axis="columns",
    sort=False
)

# Review the resulting DataFrame
display(all_neighborhoods_df.head())
display(all_neighborhoods_df.tail())


Lat         Lon  sale_price_sqr_foot   gross_rent
Alamo Square     37.791012 -122.402100           366.020712  2817.285714
Anza Vista       37.779598 -122.443451           373.382198  3031.833333
Bayview          37.734670 -122.401060           204.588623  2318.400000
Bayview Heights  37.728740 -122.410980           590.792839  3739.000000
Bernal Heights   37.728630 -122.443050                  NaN          NaN

Lat        Lon  sale_price_sqr_foot   gross_rent
Yerba Buena      37.79298 -122.39636           576.709848  2555.166667
Bernal Heights        NaN        NaN           576.746488  3080.333333
Downtown              NaN        NaN           391.434378  2817.285714
Ingleside             NaN        NaN           367.895144  2509.000000
Outer Richmond        NaN        NaN           473.900773  2817.285714

In [513]:
# Call the dropna function to remove any neighborhoods that do not have data
all_neighborhoods_df = all_neighborhoods_df.reset_index().dropna()

# Rename the "index" column as "Neighborhood" for use in the visualisation
all_neighborhoods_df = all_neighborhoods_df.rename(columns={"index": "Neighborhood"})

# Review the resulting DataFrame
display(all_neighborhoods_df.head())
display(all_neighborhoods_df.tail())

Neighborhood        Lat         Lon  sale_price_sqr_foot   gross_rent
0      Alamo Square  37.791012 -122.402100           366.020712  2817.285714
1        Anza Vista  37.779598 -122.443451           373.382198  3031.833333
2           Bayview  37.734670 -122.401060           204.588623  2318.400000
3   Bayview Heights  37.728740 -122.410980           590.792839  3739.000000
5  Buena Vista Park  37.768160 -122.439330           452.680591  2698.833333

Neighborhood       Lat         Lon  sale_price_sqr_foot   gross_rent
68         West Portal  37.74026 -122.463880           498.488485  2515.500000
69    Western Addition  37.79298 -122.435790           307.562201  2555.166667
70  Westwood Highlands  37.73470 -122.456854           533.703935  2250.500000
71       Westwood Park  37.73415 -122.457000           687.087575  3959.000000
72         Yerba Buena  37.79298 -122.396360           576.709848  2555.166667

### Step 4: Using hvPlot with GeoViews enabled, create a `points` plot for the `all_neighborhoods_df` DataFrame. Be sure to do the following:

* Set the `geo` parameter to True.
* Set the `size` parameter to “sale_price_sqr_foot”.
* Set the `color` parameter to “gross_rent”.
* Set the `frame_width` parameter to 700.
* Set the `frame_height` parameter to 500.
* Include a descriptive title.

In [514]:
# Show a map of each neighborhood. Bubble are used to indicate the neighborhood's location on the map.
# The Bubble size indicates the comparative Sale Price Per Square Foot.
# The colour shade of the bubble represents Average Gross Rent By Neighborhood

# Create a plot to analyse neighborhood info
fig4 = all_neighborhoods_df.hvplot.points(
    x='Lon',                        # Longitude coordinate on x axis
    y='Lat',                        # Latitude coordinate on y axis
    xlabel="Longitute",             # Label the x axis
    ylabel="Latitude",              # Label the y axis
    clabel = "Average Gross Rent",
    geo=True,                       # Enable GeoViews
    size='sale_price_sqr_foot',     # Set bubble size to be based off the sales price per sq ft
    color='gross_rent',             # Set the colour scale to be based on the gross rent
    tiles='OSM',                    # Show the Open Street Map (OSM)
    frame_width=700,                # Set the frame width
    frame_height=500,               # Set the frame height
    title='Figure 4 - Sale Price Per Square Foot and Average Gross Rent By Neighborhood', # Set the title
    yformatter='%.2f',              # Format the numbers to avoid scientific notation
    hover_cols=['Neighborhood', 'sale_price_sqr_foot', 'gross_rent'], # Include extra details in the hover panel
    use_index=False                  # Exclude the index from the hover data pop-up
)

display(fig4) # Display the plot

:Overlay
   .Tiles.I  :Tiles   [x,y]
   .Points.I :Points   [Lon,Lat]   (gross_rent,sale_price_sqr_foot,Neighborhood)

**Figure 4 Legend**   
Bubble Size: Sale Price Per Square Foot   
Colour Shade: Average Gross Rent By Neighborhood   

### Step 5: Use the interactive map to answer the following question:

**Question:** Which neighborhood has the highest gross rent, and which has the highest sale price per square foot?

**Answer:** The neighborhood which has the highest gross rent appears to be **Westwood Park** at `$3959` indicated by the dark blue bubble in the south west quadrant (coordinates -122.4570 longitude, 37.7342 latitude). Whereas the highest sale price per square foot seems to be **Union Square District** at `$903.99` indicated by the largest bubble in the north east quadrant of the map (coordinates -122.4021 longitude, 37.7910 latitude).

## Compose Your Data Story

Based on the visualisations that you have created, compose a data story that synthesizes your analysis by answering the following questions:

**Question:**  How does the trend in rental income growth compare to the trend in sales prices? Does this same trend hold true for all the neighborhoods across San Francisco?

**Answer:** Figure 2 suggests that the average rental income for the San Francisco county between 2010 and 2016 grew by 254%, while average sales prices grew by only 89% for the same period. This trend does not hold true for all the neighborhoods across San Francisco, by observation using Figure 3. Sales prices for some neighborhoods had negative returns, the lowest being -71% drop in value while the highest was 412% return. Gross rental return varied from stagnant (ie no increase) to 254% growth.


**Question:** What insights can you share with your company about the potential one-click, buy-and-rent strategy that they're pursuing? Do neighborhoods exist that you would suggest for investment, and why?

**Answer:** Investors using buy-and-rent strategies would be seeking the highest rental yields and a growth in property value. The south areas of San Francisco appear to be earning high gross rental incomes. However when considering the cost of purchase and therefore the rental yield, the areas in the south east appear to have better returns. Further analysis presented below suggests `Visitacion Valley` would be a neighborhood to consider investing in for the following reasons:
* Vistacion Valley has had favourable yield at an average of 12 times sales price
* Although Vistacion Valley experienced a dip in sales price in 2014, there has since been positive growth in sales prices.
* Growth in gross rent has consistently increased since 2013.

---

# Additional Analysis

In [493]:
# Create a data frame with an added column containing the rental yield (ie rental return percentage of the purchase price)
all_neighborhood_info_df_with_yield = all_neighborhood_info_df

all_neighborhood_info_df_with_yield["yield"] = all_neighborhood_info_df_with_yield["gross_rent"] /  all_neighborhood_info_df_with_yield["sale_price_sqr_foot"]

In [491]:
all_neighborhood_info_df_with_yield.nlargest(10, "yield")

sale_price_sqr_foot   gross_rent      yield
neighborhood                                                  
Silver Terrace              170.292549  3528.000000  20.717289
Hunters Point               170.624920  2489.000000  14.587553
Outer Mission               242.370952  2995.750000  12.360186
Visitacion Valley           301.466180  3657.000000  12.130714
Bayview                     204.588623  2318.400000  11.332008
Croker Amazon               303.004184  2698.833333   8.906918
Western Addition            307.562201  2555.166667   8.307805
Anza Vista                  373.382198  3031.833333   8.119919
Hayes Valley                355.932828  2817.285714   7.915217
Excelsior                   388.765927  3031.833333   7.798609

In [496]:
all_neighborhood_info_df_with_yield.nlargest(10, "gross_rent")

sale_price_sqr_foot   gross_rent      yield
neighborhood                                                  
Westwood Park               687.087575  3959.000000   5.762002
Bayview Heights             590.792839  3739.000000   6.328784
Visitacion Valley           301.466180  3657.000000  12.130714
Silver Terrace              170.292549  3528.000000  20.717289
Merced Heights              788.844818  3414.000000   4.327847
Inner Parkside              519.385604  3224.000000   6.207334
Mission Terrace             523.466201  3173.400000   6.062283
Bernal Heights              576.746488  3080.333333   5.340879
Anza Vista                  373.382198  3031.833333   8.119919
Excelsior                   388.765927  3031.833333   7.798609

In [515]:
# Using the Pandas `concat` function, join the 
# neighborhood_locations_df and the all_neighborhood_info_df DataFrame
# The axis of the concatenation is "columns".
# The concat function will automatially combine columns with
# identical information, while keeping the additional columns.
all_neighborhoods_yield_df = pd.concat(
    [neighborhood_locations_df, all_neighborhood_info_df_with_yield], 
    axis="columns",
    sort=False
)

# Review the resulting DataFrame
display(all_neighborhoods_yield_df.head())
display(all_neighborhoods_yield_df.tail())

Lat         Lon  sale_price_sqr_foot   gross_rent  \
Alamo Square     37.791012 -122.402100           366.020712  2817.285714   
Anza Vista       37.779598 -122.443451           373.382198  3031.833333   
Bayview          37.734670 -122.401060           204.588623  2318.400000   
Bayview Heights  37.728740 -122.410980           590.792839  3739.000000   
Bernal Heights   37.728630 -122.443050                  NaN          NaN   

                     yield  
Alamo Square      7.697066  
Anza Vista        8.119919  
Bayview          11.332008  
Bayview Heights   6.328784  
Bernal Heights         NaN

Lat        Lon  sale_price_sqr_foot   gross_rent  \
Yerba Buena      37.79298 -122.39636           576.709848  2555.166667   
Bernal Heights        NaN        NaN           576.746488  3080.333333   
Downtown              NaN        NaN           391.434378  2817.285714   
Ingleside             NaN        NaN           367.895144  2509.000000   
Outer Richmond        NaN        NaN           473.900773  2817.285714   

                    yield  
Yerba Buena      4.430593  
Bernal Heights   5.340879  
Downtown         7.197338  
Ingleside        6.819878  
Outer Richmond   5.944885

In [516]:
# Call the dropna function to remove any neighborhoods that do not have data
all_neighborhoods_yield_df = all_neighborhoods_yield_df.reset_index().dropna()

# Rename the "index" column as "Neighborhood" for use in the visualisation
all_neighborhoods_yield_df = all_neighborhoods_yield_df.rename(columns={"index": "Neighborhood"})

# Review the resulting DataFrame
display(all_neighborhoods_yield_df.head())
display(all_neighborhoods_yield_df.tail())

Neighborhood        Lat         Lon  sale_price_sqr_foot   gross_rent  \
0      Alamo Square  37.791012 -122.402100           366.020712  2817.285714   
1        Anza Vista  37.779598 -122.443451           373.382198  3031.833333   
2           Bayview  37.734670 -122.401060           204.588623  2318.400000   
3   Bayview Heights  37.728740 -122.410980           590.792839  3739.000000   
5  Buena Vista Park  37.768160 -122.439330           452.680591  2698.833333   

       yield  
0   7.697066  
1   8.119919  
2  11.332008  
3   6.328784  
5   5.961893

Neighborhood       Lat         Lon  sale_price_sqr_foot  \
68         West Portal  37.74026 -122.463880           498.488485   
69    Western Addition  37.79298 -122.435790           307.562201   
70  Westwood Highlands  37.73470 -122.456854           533.703935   
71       Westwood Park  37.73415 -122.457000           687.087575   
72         Yerba Buena  37.79298 -122.396360           576.709848   

     gross_rent     yield  
68  2515.500000  5.046255  
69  2555.166667  8.307805  
70  2250.500000  4.216757  
71  3959.000000  5.762002  
72  2555.166667  4.430593

In [517]:
# Show a map of each neighborhood with a colour shade representing the rental yield.

# Create a plot to analyse neighborhood info
fig5 = all_neighborhoods_yield_df.hvplot.points(
    x='Lon',                        # Longitude coordinate on x axis
    y='Lat',                        # Latitude coordinate on y axis
    xlabel="Longitute",             # Label the x axis
    ylabel="Latitude",              # Label the y axis
    clabel = "Yield",
    geo=True,                       # Enable GeoViews
    size=200,                       # Set bubble size to a fixed value since we are using the colour shading
    color='yield',                  # Set the colour scale to be based on the gross rent
    tiles='OSM',                    # Show the Open Street Map (OSM)
    frame_width=700,                # Set the frame width
    frame_height=500,               # Set the frame height
    title='Figure 5 - Yield By Neighborhood', # Set the title
    yformatter='%.2f',              # Format the numbers to avoid scientific notation
    hover_cols=['Neighborhood', 'sale_price_sqr_foot', 'gross_rent', 'yield'], # Include extra details in the hover panel
    use_index=False                  # Exclude the index from the hover data pop-up
)

display(fig5) # Display the plot

:Overlay
   .Tiles.I  :Tiles   [x,y]
   .Points.I :Points   [Lon,Lat]   (yield,Neighborhood,sale_price_sqr_foot,gross_rent)

## Compare rental yield and sales turnover
Using Figure 5, by obvervation, the south east area indicates higher rental yields.

## Check sales history of candidate neighborhoods
Checking the sales history of neighborhoods of potential interest, so that the investor is confident there is a decent property market for entry. Neighborhoods with high yield and little history may not offer true representation.

### Check Silver Terrace

In [557]:
all_neighborhoods_yield_df.query('Neighborhood == "Silver Terrace"') # Show yield information for the selected neighborhood

Neighborhood       Lat        Lon  sale_price_sqr_foot  gross_rent  \
59  Silver Terrace  37.73467 -122.40106           170.292549      3528.0   

        yield  
59  20.717289

In [564]:
prices_by_year_by_neighborhood.query('neighborhood == "Silver Terrace"') # Show sales and gross rent history over the years

sale_price_sqr_foot  gross_rent
year neighborhood                                   
2014 Silver Terrace           170.292549      3528.0

Silver Terrace had the highest rental yield, at 20.7 times sales price, however there were no further sales in the following years raising concerns of market liquidity.

---

### Check Hunters Point

In [558]:
all_neighborhoods_yield_df.query('Neighborhood == "Hunters Point"') # Show yield information for the selected neighborhood

Neighborhood       Lat        Lon  sale_price_sqr_foot  gross_rent  \
24  Hunters Point  37.72551 -122.37178            170.62492      2489.0   

        yield  
24  14.587553

In [561]:
prices_by_year_by_neighborhood.query('neighborhood == "Hunters Point"') # Show sales and gross rent history over the years

sale_price_sqr_foot  gross_rent
year neighborhood                                  
2010 Hunters Point            170.62492      1239.0
2015 Hunters Point                  NaN      3739.0

Rental yeild in Hunters Point had a respectable 14.6 times sale price, however insufficient history raises concern.

---

### Check Outer Mission

In [559]:
all_neighborhoods_yield_df.query('Neighborhood == "Outer Mission"') # Show yield information for the selected neighborhood

Neighborhood      Lat        Lon  sale_price_sqr_foot  gross_rent  \
47  Outer Mission  37.7228 -122.43869           242.370952     2995.75   

        yield  
47  12.360186

In [562]:
prices_by_year_by_neighborhood.query('neighborhood == "Outer Mission"') # Show sales and gross rent history over the years

sale_price_sqr_foot  gross_rent
year neighborhood                                  
2011 Outer Mission           142.142568      1530.0
2012 Outer Mission           221.881139      2324.0
2015 Outer Mission           564.687476      3739.0
2016 Outer Mission            40.772625      4390.0

Outer Mission saw a significant drop in sales price between 2015 and 2016, which could be seen as a buying opportunity or a red flag for concern, depending on the cause of the drop. Further investigation into the reason would be required before making any recommendations for Outer Mission.   

---

### Check Visitacion Valley

In [560]:
all_neighborhoods_yield_df.query('Neighborhood == "Visitacion Valley"') # Show yield information for the selected neighborhood

Neighborhood       Lat        Lon  sale_price_sqr_foot  gross_rent  \
67  Visitacion Valley  37.72874 -122.41098            301.46618      3657.0   

        yield  
67  12.130714

In [563]:
prices_by_year_by_neighborhood.query('neighborhood == "Visitacion Valley"') # Show sales and gross rent history over the years

sale_price_sqr_foot  gross_rent
year neighborhood                                      
2013 Visitacion Valley           293.298372      2971.0
2014 Visitacion Valley           282.025468      3528.0
2015 Visitacion Valley           302.221873      3739.0
2016 Visitacion Valley           328.319007      4390.0

Vistacion Valley had favourable yield at average 12 times sales price. Although a Vistacion Valley experienced a dip in sales price in 2014, there has since been positive growth in sales prices. Growth in gross rent has consistently increased since 2013. 